FoodOrder/Controllers/CRUD/CategoryCRUDController.cs
using FoodOrder.DAL;
using FoodOrder.Interfaces.Abstract;
using FoodOrder.ViewModel.CRUD;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace FoodOrder.Controllers.CRUD
{
    public class CategoryCRUDController : Controller
    {
        private ICategoryRepository categoryRepository;

        public CategoryCRUDController(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        // GET: CategoryCRUD
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult GetAll()
        {
            var model = categoryRepository.GetAll()
                .Select(s => new CategoryCRUDViewModel
                {
                    CategoryId = s.CategoryID,
                    CategoryName = s.CategoryName,
                    IsDeleted = s.isDeleted
                })
                .ToList();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Add(CategoryCRUDViewModel model)
        {
            categoryRepository.Add(new Category
            {
                CategoryName = model.CategoryName,
                isDeleted = false
            });

            return RedirectToAction("GetAll");
        }

        public ActionResult Delete(int? categoryId)
        {
            if (categoryId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (!categoryRepository.Remove(categoryId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return RedirectToAction("GetAll");
        }

        [HttpPost]
        public ActionResult Edit(CategoryCRUDViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return RedirectToAction("GetAll");
            }

            Category category = new Category
            {
                CategoryID = model.CategoryId,
                CategoryName = model.CategoryName,
                isDeleted = model.IsDeleted
            };

            categoryRepository.Edit(category);

            return RedirectToAction("GetAll");

        }
    }
}

FoodOrder/Controllers/CRUD/EmployeeCRUDController.cs
using FoodOrder.DAL;
using FoodOrder.Interfaces.Abstract;
using FoodOrder.ViewModel.CRUD;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FoodOrder.Controllers.CRUD
{
    public class EmployeeCRUDController : Controller
    {
        private IEmployeeRepository employeeRepository;

        public EmployeeCRUDController(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository;
        }
        // GET: EmployeeCRUD
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAll()
        {
            var model = employeeRepository.GetAll()
                .Select(t => new EmployeeCRUDViewModel
                {
                    City = t.City,
                    Email = t.Email,
                    EmployeeID = t.EmployeeID,
                    FirstName = t.FirstName,
                    HireDate = t.HireDate.ToLongDateString(),
                    IsDeleted = t.IsDeleted,
                    LastName = t.LastName,
                    Phone = t.Phone,
                    PostCode = t.PostCode,
                    Role = t.Role.ToString(),
                    Salary = t.Salary,
                    Street = t.Street
                })
                .ToList();

            return PartialView("GetAll", model);
        }

        public ActionResult GetById(int? employeeId)
        {
            if(employeeId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Employee employee = employeeRepository.GetById(employeeId);

            EmployeeCRUDViewModel model = new EmployeeCRUDViewModel
            {
                City = employee.City,
                Email = employee.Email,
                EmployeeID = employee.EmployeeID,
                FirstName = employee.FirstName,
                HireDate = employee.HireDate.ToLongDateString(),
                IsDeleted = employee.IsDeleted,
                LastName = employee.LastName,
                Phone = employee.Phone,
                PostCode = employee.PostCode,
                Role = employee.Role.ToString(),
                Salary = employee.Salary,
                Street = employee.Street
            };

            return Json(model, JsonRequestBehavior.AllowGet);
                
        }

        public ActionResult Delete(int? employeeId)
        {
            if(employeeId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            employeeRepository.Remove(employeeId);

            return RedirectToAction("GetAll");
        }
    }
}

FoodOrder/Views/EmployeeCRUD/GetAll.cshtml
@model IEnumerable<FoodOrder.ViewModel.CRUD.EmployeeCRUDViewModel>


@foreach(var i in Model)
{
    <tr>
        <td>@i.EmployeeID</td>
        <td>@i.FirstName</td>
        <td>@i.LastName</td>
        <td>@i.Email</td>
        <td>
            @Ajax.ActionLink("Delete", "Delete", new { employeeId = @i.EmployeeID }, new AjaxOptions
       {
           UpdateTargetId = "employeeTableBody"
       })
        </td>
        <td>
            @Ajax.ActionLink("Details", "GetById", new { employeeId = @i.EmployeeID }, new AjaxOptions
       {
           OnSuccess = "Details"
       })
    </td>
    </tr>
}

FoodOrder/Views/EmployeeCRUD/Index.cshtml
@model FoodOrder.ViewModel.CRUD.EmployeeCRUDViewModel
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<script src="~/Scripts/jquery-3.1.1.js"></script>
<div>
    <h3>Employee</h3>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>First Name</th>
                <th>Last name</th>
                <th>E-mail</th>
                <th>Delete</th>
                <th>Details</th>
            </tr>
        </thead>

        <tbody id="employeeTableBody">
            @Html.Action("GetAll", "EmployeeCRUD")
        </tbody>
    </table>

    <div class="btn-group">

        @Ajax.ActionLink("Refresh", "GetAll", null, new AjaxOptions
   {
       UpdateTargetId = "employeeTableBody"
   }, new { @class = "btn btn-primary" })

    </div>
</div>

<div class="modal fade" id="addModal" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><b>Add Category</b></h4>
            </div>



            @using (Ajax.BeginForm("Add", "CategoryCRUD", new AjaxOptions
            {
                HttpMethod = "POST",
                UpdateTargetId = "employeeTableBody",
                OnSuccess = "CreateSuccess"
            }))
            {
                <div class="modal-body">
                    <div class="form-group">
                      
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-danger" value="Add" />
                    </div>
                </div>
            }
        </div>

    </div>
</div>

<div class="modal fade" id="detailsModal" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><b>Details</b></h4>
            </div>


            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Employee Id:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailEmployeeId"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">First Name:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailFirstName"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Last Name:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailLastName"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">E-mail:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailEmail"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">City:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailCity"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Street:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailStreet"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Post Code:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailPostCode"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Phone:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailPhone"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Hire Date:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailHireDate"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Salary:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailSalary"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Role:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailRole"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-4" for="email">Is Deleted?:</label>
                    <div class="col-lg-8">
                        <p class="form-control-static" id="detailIsDeleted"></p>
                    </div>
                </div>

             
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<script>

    function Details(data)
    {
        $("#detailEmployeeId").text(data.EmployeeID);
        $("#detailFirstName").text(data.FirstName);
        $("#detailLastName").text(data.LastName);
        $("#detailCity").text(data.City);
        $("#detailStreet").text(data.Street);
        $("#detailPostCode").text(data.PostCode);
        $("#detailEmail").text(data.Email);
        $("#detailPhone").text(data.Phone);
        $("#detailRole").text(data.Role);
        $("#detailSalary").text(data.Salary);
        $("#detailHireDate").text(data.HireDate);

        if (data.IsDeleted) {
            $("#detailIsDeleted").empty().append('<button class="btn btn-success btn-circle" title="YES"><span class="glyphicon glyphicon-ok"></span></button>');
        }
        else {
            $("#detailIsDeleted").empty().append('<button class="btn btn-danger btn-circle" title="NO"><span class="glyphicon glyphicon-remove"></span></button>');
        }
        jQuery.noConflict();
        $("#detailsModal").modal("show");

    }


</script>