FoodOrder/Models/Cart.cs
using FoodOrder.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FoodOrder.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        public void AddProduct(Product product, int quantity,decimal price)
        {
            var cartLine = new CartLine();
         
            cartLine = lineCollection
                .Where(t => t.Product.ProductID == product.ProductID)
                .FirstOrDefault();

            if (cartLine == null)
            {
                lineCollection.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity,
                    Price = price
                });
            }
            else
            {
                cartLine.Quantity += quantity;
            }
        }

        public void RemoveProduct(Product product)
        {
            lineCollection.RemoveAll(t => t.Product.ProductID == product.ProductID);
        }

        public decimal TotalValue()
        {
            return lineCollection.Sum(t => t.Quantity * t.Price);
        }

        public void Clear()
        {
            lineCollection.Clear();
        }

        public List<CartLine> Lines { get { return lineCollection; } }

    }

    public class CartLine
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    }
}

FoodOrder/Controllers/CartController.cs
using FoodOrder.DAL;
using FoodOrder.Interfaces.Abstract;
using FoodOrder.Models;
using FoodOrder.ViewModel.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodOrder.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository productRepository;
        private IPriceRepository priceRepository;

        public CartController(IProductRepository productRepository, IPriceRepository priceRepository)
        {
            this.productRepository = productRepository;
            this.priceRepository = priceRepository;
        }
        // GET: Cart
        public ActionResult ShowCart()
        {
            return View();
        }

        public ActionResult ShowCartDataTable()
        {
            CartViewModel model = new CartViewModel();
            List<CartLine> data = GetCart().Lines;

            foreach (var i in data)
            {
                model.CartLine.Add(new CartLineViewModel()
                {
                    ProductId = i.Product.ProductID,
                    Price = i.Price,
                    ProductName = i.Product.ProductName,
                    Quantity = i.Quantity
                });
            }
            model.TotalValue = GetCart().TotalValue();

            if (!model.CartLine.Any())
            {
                ViewBag.CartEmpty = "Cart Empty!";
            }
            
            return PartialView(model);
        }

        public ActionResult ShowPartialCart()
        {
            CartViewModel model = new CartViewModel();
            List<CartLine> data = GetCart().Lines;

            foreach (var i in data)
            {
                model.CartLine.Add(new CartLineViewModel()
                {
                    ProductId = i.Product.ProductID,
                    Price = i.Price,
                    ProductName = i.Product.ProductName,
                    Quantity = i.Quantity
                });
            }
            model.TotalValue = GetCart().TotalValue();

            if (!model.CartLine.Any())
            {
                ViewBag.CartEmpty = "Cart empty!";
            }

            return PartialView(model);
        }

        public ActionResult AddToCart(int productId)
        {
            Product product = productRepository.GetById(productId);

            decimal price = priceRepository.GetAll()
                .Where(t => t.Product.ProductID == productId && t.EndDate == null)
                .Select(x => x.Value)
                .FirstOrDefault();

            if (product != null)
            {
                GetCart().AddProduct(product, 1, price);
            }

            return RedirectToAction("ShowPartialCart", "Cart");
        }

        public ActionResult RemoveFromCart(int productId, string returnUrl = "ShowPartialCart")
        {
            Product product = productRepository.GetById(productId);

            if (product != null)
            {
                GetCart().RemoveProduct(product);
            }
            return RedirectToAction(returnUrl, "Cart");
        }

        public ActionResult ClearCart(string returnUrl)
        {
            GetCart().Clear();
            return RedirectToAction(returnUrl, "Cart");
        }

        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];

            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
    }
}

FoodOrder/Controllers/OrderManageController.cs
using FoodOrder.DAL;
using FoodOrder.Infrastructure;
using FoodOrder.Interfaces;
using FoodOrder.Interfaces.Abstract;
using FoodOrder.Models;
using FoodOrder.ViewModel.OrderManage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FoodOrder.Controllers
{
    public class OrderManageController : Controller
    {
        private ICustomerRepository customerRepository;
        private IOrderRepository orderRepository;
        private IOrderLineRepository orderLineRepository;
        private IEmailSender emailSender;

        public OrderManageController(ICustomerRepository customerRepository, IOrderRepository orderRepository,
            IOrderLineRepository orderLineRepository, IEmailSender emailSender)
        {
            this.customerRepository = customerRepository;
            this.orderRepository = orderRepository;
            this.orderLineRepository = orderLineRepository;
            this.emailSender = emailSender;
        }


        [CustomAuthorize(Roles = "Customer")]
        public ActionResult OrderDetails()
        {
            string currentUserName = HttpContext.User.Identity.Name;
          
            Customer customer = customerRepository.GetByEmail(currentUserName);

            if (customer == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            decimal cartValue = cart.TotalValue();

            List<OrderLineViewModel> cartLines = new List<OrderLineViewModel>();
            foreach (var i in cart.Lines)
            {
                cartLines.Add(new OrderLineViewModel
                {
                    ProductId = i.Product.ProductID,
                    Quantity = i.Quantity,
                    Price = i.Price,
                    ProductName = i.Product.ProductName
                });
            }

            var model = new OrderDetailsViewModel()
            {
                CustomerId = customer.CustomerID,
                CustomerFirstName = customer.FirstName,
                CustomerLastName = customer.LastName,
                ShipCity = customer.City,
                ShipStreet = customer.Street,
                PostCode = customer.PostCode,
                Phone = customer.Phone,
                Value = cartValue,
                CartLines = cartLines,
                CustomerEmail = customer.EMail
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult OrderDetails(OrderDetailsViewModel model)
        {
            int orderId;

            if (model.DeliveryMethod != DeliveryMethod.SelfPickup)
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var order = new Order
                {
                    CustomerId = model.CustomerId,
                    DeliveryMethod = model.DeliveryMethod,
                    OrderDate = DateTime.Now,
                    PaymentMethod = model.PaymentMethod,
                    ShipCity = model.ShipCity,
                    ShipStreet = model.ShipStreet,
                    ShipPostCode = model.PostCode,
                    Value = model.Value
                };

                orderRepository.Add(order);

                orderId = order.OrderID;
            }
            else
            {
                var order = new Order
                {
                    CustomerId = model.CustomerId,
                    DeliveryMethod = model.DeliveryMethod,
                    OrderDate = DateTime.Now,
                    PaymentMethod = model.PaymentMethod,
                    ShipCity = "-",
                    ShipStreet = "-",
                    ShipPostCode = "-",
                    Value = model.Value
                };

                orderRepository.Add(order);

                orderId = order.OrderID;
            }

            foreach (var i in model.CartLines)
            {
                orderLineRepository.Add(new OrderLine
                {
                    ProductId = i.ProductId,
                    Quantity = i.Quantity,
                    OrderId = orderId,
                    LineValue = i.Price * i.Quantity,
                    UnitPrice = i.Price
                });
            }

            emailSender.SendEmail(model.CustomerEmail, "Order",
                EmailsBody.SubmitOrder(model.CustomerFirstName, model.CustomerEmail, model.Value));            

            TempData["AddOrderSuccess"] = "Your order is being processed";
            return View("Success");

        }

        [CustomAuthorize(Roles = "Customer")]
        public ActionResult UserOrders()
        {
            string currentUserName = HttpContext.User.Identity.Name;
            
            int customerId = customerRepository.GetByEmail(currentUserName).CustomerID;

            var model = orderRepository.GetAll()
                .Where(t => t.CustomerId == customerId)
                .OrderByDescending(t => t.OrderDate)
                .Select(s => new UserOrdersViewModel
                {
                    OrderDate = s.OrderDate,
                    OrderValue = s.Value,
                    OrderLines = s.OrderLines
                    .Select(t => new OrderLineViewModel
                    {
                        Price = t.UnitPrice,
                        ProductId = t.ProductId,
                        ProductName = t.Product.ProductName,
                        Quantity = t.Quantity
                    })
                    .ToList()
                })
                .ToList();            

            return View(model);
        }
    }
}

FoodOrder/Views/Cart/ShowCart.cshtml
@model FoodOrder.ViewModel.Cart.CartViewModel
@{
    ViewBag.Title = "ShowCart";
}

<div class="col-lg-12" style="font-size:x-large">
    <h2>Cart</h2>

    <table class="table table-condensed" id="tableBodyShowCart">
        @Html.Action("ShowCartDataTable", "Cart")
    </table>

    <div>
        <a href="@Url.Action("OrderDetails","OrderManage")">
            <input type="submit" class="btn btn-primary" value="Checkout" />
        </a>
    </div>
</div>

FoodOrder/Views/Cart/ShowCartDataTable.cshtml
@model FoodOrder.ViewModel.Cart.CartViewModel

<h2>@ViewBag.CartEmpty</h2>
<thead>
    <tr>
        <th>Quantity</th>
        <th>Name</th>
        <th>Price</th>
        <th>Value</th>
        <th></th>
    </tr>
</thead>

<tbody>
    @foreach (var i in Model.CartLine)
            {
        <tr>
            <td>@i.Quantity</td>
            <td>@i.ProductName</td>
            <td>@i.Price</td>
            <td>@((@i.Price * @i.Quantity))</td>
            <td>
                @Ajax.ActionLink(" ", "RemoveFromCart", "Cart", new { productId = @i.ProductId, returnUrl = "ShowCartDataTable" }, new AjaxOptions
           {
               UpdateTargetId = "tableBodyShowCart"
           }, new { @class = "fa fa-times", @title = "Delete"})
            </td>
        </tr>
    }
</tbody>
<tfoot>
    <tr>
        <td colspan="3" align="right" style="font-weight:bolder">Total:</td>
        <td style="font-weight:bold">@Model.TotalValue</td>
    </tr>
</tfoot>

FoodOrder/Views/Cart/ShowPartialCart.cshtml
@model FoodOrder.ViewModel.Cart.CartViewModel

@*<div class="dropdown">
        <button class="btn btn-toolbar dropdown-toggle" type="button" data-toggle="dropdown">
            <span class="fa fa-shopping-cart"></span>
            <span class="badge">@Model.TotalValue</span>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li>
                <label></label>
                <label>Product</label>
                <label>Price</label>
                <label>Quantity</label>
            </li>
            @foreach (var i in Model.CartLine)
            {
                <li>
                    <div>
                        <h4>

                            @Ajax.ActionLink(" ", "RemoveFromCart", "Cart", new { productId = @i.ProductId }, new AjaxOptions
                       {
                           UpdateTargetId = "shoppingCart"
                       }, new { @class = "fa fa-times",@title = "Delete" })

                            <text>@i.ProductName</text>
                            <text>@i.Price</text>
                            <text>@i.Quantity</text>

                        </h4>
                    </div>
                </li>
            }
            <text>@ViewBag.CartEmpty</text>
            <li>
                <a>
                    @Html.ActionLink("Continue", "ShowCart", "Cart", new { @class = "btn btn-primary" })
                </a>
                <a>
                    @Ajax.ActionLink("Clear", "ClearCart", "Cart", new { returnUrl = "ShowPartialCart" }, new AjaxOptions
               {
                   UpdateTargetId = "shoppingCart"
               },
               new { @class = "btn btn-danger" })
                </a>
            </li>
        </ul>
    </div>*@

<div class="dropdown">


    <div class="fa fa-3x fa-shopping-cart cartIcon"></div>
    <div class="cartBadge">@Model.TotalValue</div>
    <div class="fa fa-caret-down fa-2x cartDown" data-toggle="dropdown"></div>


    <ul class="dropdown-menu">
        <li>
            <label></label>
            <label>Product</label>
            <label>Price</label>
            <label>Quantity</label>
        </li>
        @foreach (var i in Model.CartLine)
            {
            <li>
                <div>
                    <h4>

                        @Ajax.ActionLink(" ", "RemoveFromCart", "Cart", new { productId = @i.ProductId }, new AjaxOptions
                       {
                           UpdateTargetId = "shoppingCart"
                       }, new { @class = "fa fa-times", @title = "Delete" })

                        <text>@i.ProductName</text>
                        <text>@i.Price</text>
                        <text>@i.Quantity</text>

                    </h4>
                </div>
            </li>
        }
        <text>@ViewBag.CartEmpty</text>
        <li>
            <a>
                @Html.ActionLink("Continue", "ShowCart", "Cart", new { @class = "btn btn-primary" })
            </a>
            <a>
                @Ajax.ActionLink("Clear", "ClearCart", "Cart", new { returnUrl = "ShowPartialCart" }, new AjaxOptions
               {
                   UpdateTargetId = "shoppingCart"
               },
               new { @class = "btn btn-danger" })
            </a>
        </li>
    </ul>
</div>